# Generated by Django 5.2.8 on 2025-12-19 17:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_notificacionstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_credito',
            field=models.BooleanField(default=False, help_text='Si es crédito, se creará una cuenta por cobrar', verbose_name='Venta a Crédito'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Cliente (Legacy)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('credito', 'Crédito'), ('mixto', 'Mixto')], default='efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Almacén')),
                ('codigo', models.CharField(help_text='Código único del almacén', max_length=20, unique=True, verbose_name='Código')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='inventario__codigo_d0184d_idx'), models.Index(fields=['activo'], name='inventario__activo_f7ee63_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre o Razón Social')),
                ('rut', models.CharField(blank=True, help_text='RUT del cliente (opcional)', max_length=20, null=True, unique=True, verbose_name='RUT')),
                ('tipo_cliente', models.CharField(choices=[('natural', 'Persona Natural'), ('empresa', 'Empresa')], default='natural', max_length=20, verbose_name='Tipo de Cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('contacto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona de Contacto')),
                ('limite_credito', models.DecimalField(decimal_places=0, default=0, help_text='Monto máximo de crédito permitido (0 = sin límite)', max_digits=12, verbose_name='Límite de Crédito')),
                ('activo', models.BooleanField(default=True, help_text='Cliente activo en el sistema', verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='inventario__nombre_8f71a9_idx'), models.Index(fields=['rut'], name='inventario__rut_c4bea3_idx'), models.Index(fields=['activo'], name='inventario__activo_cac698_idx')],
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='inventario.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='inventario.cliente', verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número de Documento')),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto Total')),
                ('monto_pagado', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto Pagado')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='inventario.cliente', verbose_name='Cliente')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_por_cobrar', to='inventario.venta', verbose_name='Venta Relacionada')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Número de Orden')),
                ('fecha_orden', models.DateField(verbose_name='Fecha de Orden')),
                ('fecha_esperada', models.DateField(verbose_name='Fecha Esperada de Recepción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcialmente Recibida'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='inventario.proveedor', verbose_name='Proveedor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Solicitada')),
                ('cantidad_recibida', models.IntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Item de Orden de Compra',
                'verbose_name_plural': 'Items de Orden de Compra',
            },
        ),
        migrations.CreateModel(
            name='PagoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('referencia', models.CharField(blank=True, help_text='Número de cheque, transferencia, etc.', max_length=200, null=True, verbose_name='Referencia')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('cuenta_por_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventario.cuentaporcobrar', verbose_name='Cuenta por Cobrar')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago de Cliente',
                'verbose_name_plural': 'Pagos de Clientes',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen', verbose_name='Almacén de Recepción')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='inventario.ordencompra', verbose_name='Orden de Compra')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Recepción de Mercancía',
                'verbose_name_plural': 'Recepciones de Mercancía',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='StockAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('stock_minimo', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_productos', to='inventario.almacen', verbose_name='Almacén')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_almacenes', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock por Almacén',
                'verbose_name_plural': 'Stocks por Almacén',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transferencia', models.CharField(max_length=50, unique=True, verbose_name='Número de Transferencia')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_transferencia', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Transferencia')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='inventario.almacen', verbose_name='Almacén Destino')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='inventario.almacen', verbose_name='Almacén Origen')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ItemTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('cantidad_enviada', models.IntegerField(default=0, verbose_name='Cantidad Enviada')),
                ('cantidad_recibida', models.IntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.transferencia', verbose_name='Transferencia')),
            ],
            options={
                'verbose_name': 'Item de Transferencia',
                'verbose_name_plural': 'Items de Transferencia',
            },
        ),
        migrations.AddIndex(
            model_name='cuentaporcobrar',
            index=models.Index(fields=['cliente', 'estado'], name='inventario__cliente_a0bb46_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporcobrar',
            index=models.Index(fields=['fecha_vencimiento'], name='inventario__fecha_v_51b373_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporcobrar',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='inventario__estado_c6ca02_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['proveedor', 'estado'], name='inventario__proveed_7503a2_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['fecha_orden'], name='inventario__fecha_o_db0e64_idx'),
        ),
        migrations.AddIndex(
            model_name='pagocliente',
            index=models.Index(fields=['cuenta_por_cobrar', 'fecha_pago'], name='inventario__cuenta__2ccb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalmacen',
            index=models.Index(fields=['almacen', 'producto'], name='inventario__almacen_6e8c55_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalmacen',
            index=models.Index(fields=['cantidad'], name='inventario__cantida_120610_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockalmacen',
            unique_together={('producto', 'almacen')},
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['almacen_origen', 'estado'], name='inventario__almacen_eff9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['almacen_destino', 'estado'], name='inventario__almacen_e4a316_idx'),
        ),
    ]
